---
- name: Install Dependencies
  hosts: all

- import_playbook: centos-setup.yml
  when: ansible_distribution == "CentOS"


- import_playbook: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"