---
- name: Setup for Ubuntu
  hosts: all
  become: yes
  tasks:  

    - name: Install the 'Development tools' package group
      apt:
        name: "build-essential"
        state: present

    - name: Install Python
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python3
        - python3-pip
        - python3-dev
        - nginx
        - uwsgi

  
    - name: Install Flask
      pip:
        executable: pip3
        name: "{{ packages }}"
      vars:
        packages:
        - Flask

    
    
